################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Data Commerce Solutions
  productionDescription: <p>Fiserv's Data Commerce Solutions Team announces the launch of “Fraud Risk Exchange”, an innovative platform offering real time capabilities built on Fiserv's large scale proprietary data and contributions from its consortium partners which will identify and reduce the risk of fraud. The Fraud Risk Exchange will enable an industry leading data consortium allowing Fiserv clients and its trusted partners to query and share fraud related data.</p><p>Fraud Risk Exchange is a cloud based, single application programing interface (API) based platform allowing Customers to query Fiserv’s rich fraud ecosystem to provide a likelihood of fraud response in real time for Get Ownership (account ownership verification, identity verification) use case as its initial launch. </p><p>Fraud Risk Exchange will provide responses via Get Ownership API in real-time if the Consumer data including, but not limited to, Name, Address, Email, Phone, DOB, Bank Number, Driver’s License, SSN matches with the data in FRE database. In the Phase 1, Seed data will be leveraged for account ownership (confirm the account information matches to the Customer), and identity verification (confirm that Customer information matches with the Identity who they claim to be). Based on the data match, API response back to the Client will be Yes (matches), No (it doesn’t match or partial match) or Null (unsure). The goal is to support Fiserv clients with real-time data match to enhance their risk decisioning, decrease their cost on 3rd party vendors and increase customer satisfaction while fighting fraud.</p><p>The Get Ownership API will provide risk signals based on the search and match logic for fraud/compliance use cases (Non-FCRA).</p>
  whoIsItFor: <p> Potential clients include existing Fiserv fraud product teams as well as external FIs, Credit Bureaus, Fintechs, Merchants, and Fraud Solution providers. The depth and scale of the Fraud Risk Exchange will grow over time as Clients are added to it and additional Fiserv data sources are assimilated as source data.</p>
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv logo™
getStarted: docs/getting-started.md
featuredFeatures:
  - title: Account Verification Api
    description:   "APIs that make it possible to verify Account information"
    tags: ["REPLACEME1"]
    bullets: ["REPLACEME"]  
    relatedDocs:
      - relatedDoc: 
        title: Getting started
        description: The basics of how to get started with Data Commerce Solutions
        link: docs/getting-started.md
      - relatedDoc: 
        title: release notes
        description: Our latest set of release notes
        link: docs/release-notes/2023/2023_Q3.md
    relatedAPIs:
      - relatedAPI: 
        title: Account Verification
        description: "APIs that make it possible to verify account information"
        type: "post"        
        path: "/v1/account/verification"
  - title: Merchant Verification Api
    description: "APIs that make it possible to verify merchant information"
    tags: ["REPLACEME1"]
    bullets: ["REPLACEME"]  
    relatedDocs:
      - relatedDoc: 
        title: Getting started
        description: The basics of how to get started with Data Commerce Solutions
        link: docs/getting-started.md
      - relatedDoc: 
        title: release notes
        description: Our latest set of release notes
        link: docs/release-notes/2023/2023_Q3.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Verification
        description: "APIs that make it possible to verify merchant information"
        type: "post"        
        path: "/v1/merchant/verification"
benefits:
  - title: Get Ownership API  
    description: >
      replace with description of benifit
  - title: Search & Match Logic 
    description: >
      replace with description of benifit
  - title: Seed Data (Banking & eCommerce Merchant Data)  
    description: >
      replace with description of benifit
  - title: Keying and linking 
    description: >
      replace with description of benifit 
  - title: Call a Friend 
    description: >
      replace with description of benifit
  - title: Data Analytics & Reporting 
    description: >
      replace with description of benifit
  - title: Yes/No/Null Response 
    description: >
      replace with description of benifit
  - title: Rules
    description: >
      replace with description of benifit