---
openapi: 3.0.0
info:
  title: Merchant Verification API
  description: Merchant Verification api provides merchants confirmation that they have the authority to transact provided that data elements provided by the merchant are accurate
  version: "1"
servers:
# Added by API Auto Mocking Plugin
- url: https://az-n-spring-verification-app-az-n-spring-veriapp-merchant.private.azuremicroservices.io
  description: Demo Endpoint
paths:
  /v1/merchant/verification:
    post:
      summary: Verify that a merchant has the authority to transact using the provided account and that data elements provided by the merchant are accurate
      description: verifies account information
      operationId: merchantVerification
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Authorization'
      - name: request-id 
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/request-id'
      - name: subscriber-id
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/subscriber-id'
      requestBody:
        description: merchant account parameters used for merchant verification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantVerificationRequest'
        required: true
      responses:
        "200":
          description: matching results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Response'
              examples:
                search_results_matching_criteria:
                  summary: search results matching criteria
                  description:  "This response is shown when the data provided successfully matches the merchant data in the database "
                  value:
                    tranasction:
                      transactionId: "1234576"
                      timestamp: 2023-07-12 11:01:10
                    response:
                      verified: "yes"
                      message: search results matching criteria
                no_matching_results:
                  summary: no matching results
                  description: "This response is shown when there is no result in the database matching the data provided "
                  value:
                    tranasction:
                      transactionId: 550e8400-e29b-41d4-a716
                      timestamp: 2023-07-12 11:01:10
                    response:
                      verified: "no"
                      message: no matching results
        "206":
          description: Partial results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_206'
        "207":
          description: Multiple results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_207'
        "412":
          description: Data fields not supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_412'
        "400":
          description: 'invalid data field formatting '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: "Unauthenticated response , missing or invalid token"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "403":
          description: "Forbidden , account id not on system"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
      x-group-name: Data Commerce Solutions
      x-proxy-name: Merchant Verification1
      x-child-product-name: Merchant Verification2
components:
  schemas:
    Authorization:
      type: string
      description: "Send access token to the text Bearer as follows: bearer {{access_token}}"
      example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    request-id:
      type: string
      description: uniquely identifies the specific HTTP request.
      example: requestID1
    subscriber-id:
      type: string
      description: uniquely identifies the merchants information for the request.
      example: 9338497
    MerchantVerificationRequest:
      required:
      - address
      - businessName
      type: object
      properties:
        businessName:
          $ref: '#/components/schemas/businessName'
        address:
          $ref: '#/components/schemas/address'
        phone:
          $ref: '#/components/schemas/phone'
        dunsNumber:
          $ref: '#/components/schemas/dunsNumber'
    businessName:
      type: string
      description: 'Define the Business name '
      example: Gorman Manufacturing
    address:
      required:
      - addressCode
      - addressLine1
      - city
      - country
      - zipCode
      type: array
      items:
        type: object
        properties:
          addressLine1:
            type: string
            description: "User’s address street 1. Should not be more than 30 characters. Length: 1-30"
            example: 492 KOLLER STREET
          addressLine2:
            type: string
            description: "User’s address street 2. Should not be more than 30 characters and can be blank. Length: 0-30"
            example: Barkingson Way
          city:
            type: string
            description: "User’s city. Cannot be empty. Mandatory if addressLine 1 is available. Length: 1-25"
            example: SAN FRANCISCO
          state:
            type: string
            description: "User’s state. Valid US state or territory in format “NY” for New York. Case Sensitive. Length: 2"
            example: CA
          country:
            type: string
            description: User’s country.
            example: US
          zipCode:
            type: string
            description: "User’s ZIP code. Cannot be empty. Mandatory if addressLine 1 is available. Numeric Length: 5 "
            example: "94486"
          addressCode:
            type: string
            description: "Type of address. Valid values: Home, Billing, Service, Work "
            example: Work
            enum:
            - Home
            - Billing
            - Service
            - Work
        description: 'Defines the merchants address '
    phone:
      required:
      - phoneNumber
      - phoneType
      type: object
      properties:
        phoneNumber:
          type: string
          description: "User’s phone number. It can be home, cell, or work phone. This is used for primary phone. Should be 10 digits"
          example: "1212456789"
        phoneType:
          type: string
          description: "Type of phone number provided. Valid values: Business, Home, Mobile, Personal, Landline, Work"
          example: Home
          enum:
          - Business
          - Home
          - Mobile
          - Personal
          - Landline
          - Work
      description: Define the merchants phone
    dunsNumber:
      type: string
      description: Define Merchants duns number this is an alternative way of identifying the merchant based on a unique identifier
      example: "804735132"
    "200Response":
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/Response_tranasction'
        response:
          $ref: '#/components/schemas/200Response_response'
      description: Search results matching criteria response
    inline_response_206:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_206_tranasction'
        response:
          $ref: '#/components/schemas/inline_response_206_response'
    inline_response_207:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_207_tranasction'
        response:
          $ref: '#/components/schemas/inline_response_207_response'

    inline_response_412:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_206_tranasction'
        errors:
          type: array
          description: Array containing error code and the response message
          items:
            $ref: '#/components/schemas/inline_response_412_errors'
    inline_response_400:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_206_tranasction'
        errors:
          type: array
          description: Array containing error code and the response message
          items:
            $ref: '#/components/schemas/inline_response_400_errors'
    inline_response_401:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_206_tranasction'
        errors:
          type: array
          description: Array containing error code and the response message
          items:
            $ref: '#/components/schemas/inline_response_401_errors'
    inline_response_403:
      type: object
      properties:
        tranasction:
          $ref: '#/components/schemas/inline_response_206_tranasction'
        errors:
          type: array
          description: Array containing error code and the response message
          items:
            $ref: '#/components/schemas/inline_response_403_errors'
    "Response_tranasction":
      type: object
      properties:
        transactionId:
          type: string
          description: 'Response transactionId '
        timestamp:
          type: string
          description: Response timestamp
      description: transactionid and timestamp
    "200Response_response":
      type: object
      properties:
        verified:
          type: string
          description: Yes/No value if Response has been verified
        message:
          type: string
          description: The message supplied with the Response
      description: Response information verified and message
    inline_response_207_response:
      type: object
      properties:
          verified:
            type: string
            description: Yes/No value if Response has been verified
            example: "No"
          message:
            type: string
            description: The message supplied with the Response
            example: multiple results found
    inline_response_206_tranasction:
      type: object
      properties:
        transactionId:
          type: string
          description: 'Response transactionId '
          example: 550e8400-e29b-41d4-a716-446655440000
        timestamp:
          type: string
          description: Response timestamp
          example: 2023-07-12 11:01:10
      description: transactionid and timestamp
    inline_response_206_response:
      type: object
      properties:
        verified:
          type: string
          description: Yes/No value if Response has been verified
          example: "No"
        message:
          type: string
          description: The message supplied with the Response
          example: partial results found
      description: Response information verified and message
    inline_response_207_tranasction:
      type: object
      properties:
        transactionId:
          type: string
          description: 'Response transactionId '
          example: 550e8400-e29b-41d4-a716-446655440000
        timestamp:
          type: string
          description: Response timestamp
          example: 2023-07-12 11:01:10
      description: transactionid and timestamp
    inline_response_412_errors:
      type: object
      properties:
        code:
          type: string
          description: 'the error code '
          example: "412"
        message:
          type: string
          description: The message supplied with the Response
          example: data fields not supported
    inline_response_400_errors:
      type: object
      properties:
        code:
          type: string
          description: 'the error code '
          example: "400"
        message:
          type: string
          description: The message supplied with the Response
          example: invalid data field formatting
    inline_response_401_errors:
      type: object
      properties:
        code:
          type: string
          description: 'the error code '
          example: "401"
        message:
          type: string
          description: The message supplied with the Response
          example: "Unauthenticated response, missing or invalid token"
    inline_response_403_errors:
      type: object
      properties:
        code:
          type: string
          description: 'the error code '
          example: "403"
        message:
          type: string
          description: The message supplied with the Response
          example: "Forbidden, account id not on system"