name: Studio Validator
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]

jobs:
  validator:
    #to update collections in tenant-data use @main
    #uses: Fiserv/remote-actions/.github/workflows/validator-service.yaml@main
    #to not update collections in tenant-data use @develop
    uses: Fiserv/remote-actions/.github/workflows/validator-service.yaml@develop
    secrets: inherit
 